<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Rogue_Kie.BE.Business</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MailKit" Version="4.9.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.41.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rogue-Kie.BE.DataAccess\Rogue-Kie.BE.DataAccess.csproj" />
    <ProjectReference Include="..\Rogue-Kie.BE.Contracts\Rogue-Kie.BE.Contracts.csproj" />
  </ItemGroup>

</Project>
