// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rogue_Kie.BE.DataAccess.DBContext;

#nullable disable

namespace Rogue_Kie.BE.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708034548_UpdateExistingTablesSchema")]
    partial class UpdateExistingTablesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.BuffConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuffName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BuffType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("BuffConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuffName = "Speed Boost",
                            BuffType = "StatModifier",
                            Description = "Increases movement speed.",
                            IconPath = "speed_icon",
                            Rarity = "Common",
                            Value = 1.5f
                        },
                        new
                        {
                            Id = 2,
                            BuffName = "Damage Boost",
                            BuffType = "StatModifier",
                            Description = "Increases damage dealt.",
                            IconPath = "damage_icon",
                            Rarity = "Rare",
                            Value = 2f
                        },
                        new
                        {
                            Id = 3,
                            BuffName = "Health Regen",
                            BuffType = "Utility",
                            Description = "Regenerates health over time.",
                            IconPath = "regen_icon",
                            Rarity = "Epic",
                            Value = 10f
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.BulletConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BulletName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("CritRate")
                        .HasColumnType("real");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<float>("FlightSpeed")
                        .HasColumnType("real");

                    b.Property<int>("PiercingCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("BulletConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BulletName = "Basic Bullet",
                            CritRate = 0.1f,
                            Damage = 20,
                            FlightSpeed = 10f,
                            PiercingCount = 0,
                            PrefabName = "BasicBulletPrefab"
                        },
                        new
                        {
                            Id = 2,
                            BulletName = "Buckshot",
                            CritRate = 0.05f,
                            Damage = 10,
                            FlightSpeed = 15f,
                            PiercingCount = 0,
                            PrefabName = "BuckshotPrefab"
                        },
                        new
                        {
                            Id = 3,
                            BulletName = "Sniper Round",
                            CritRate = 0.5f,
                            Damage = 150,
                            FlightSpeed = 30f,
                            PiercingCount = 3,
                            PrefabName = "SniperRoundPrefab"
                        },
                        new
                        {
                            Id = 4,
                            BulletName = "Rifle Bullet",
                            CritRate = 0.2f,
                            Damage = 30,
                            FlightSpeed = 20f,
                            PiercingCount = 1,
                            PrefabName = "RifleBulletPrefab"
                        },
                        new
                        {
                            Id = 5,
                            BulletName = "Sword Slash",
                            CritRate = 0.3f,
                            Damage = 40,
                            FlightSpeed = 5f,
                            PiercingCount = 99,
                            PrefabName = "SwordSlashPrefab"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.EnemyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EnemyConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackSpeed = 1.5f,
                            BaseDamage = 10,
                            BaseHealth = 50,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Slime",
                            MoveSpeed = 2f,
                            PrefabName = "SlimePrefab"
                        },
                        new
                        {
                            Id = 2,
                            AttackSpeed = 1.2f,
                            BaseDamage = 15,
                            BaseHealth = 100,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Goblin",
                            MoveSpeed = 3.5f,
                            PrefabName = "GoblinPrefab"
                        },
                        new
                        {
                            Id = 3,
                            AttackSpeed = 2f,
                            BaseDamage = 30,
                            BaseHealth = 250,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Orc",
                            MoveSpeed = 1.5f,
                            PrefabName = "OrcPrefab"
                        },
                        new
                        {
                            Id = 4,
                            AttackSpeed = 0.5f,
                            BaseDamage = 100,
                            BaseHealth = 1000,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Dragon",
                            MoveSpeed = 5f,
                            PrefabName = "DragonPrefab"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.LevelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LevelConfigId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DifficultyMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LevelConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyMultiplier = 1f,
                            FloorNumber = 1,
                            StageId = 1
                        },
                        new
                        {
                            Id = 2,
                            DifficultyMultiplier = 1.2f,
                            FloorNumber = 2,
                            StageId = 1
                        },
                        new
                        {
                            Id = 3,
                            DifficultyMultiplier = 1.5f,
                            FloorNumber = 3,
                            StageId = 1
                        },
                        new
                        {
                            Id = 4,
                            DifficultyMultiplier = 2f,
                            FloorNumber = 4,
                            StageId = 1
                        },
                        new
                        {
                            Id = 5,
                            DifficultyMultiplier = 3f,
                            FloorNumber = 5,
                            StageId = 1
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator - Full access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Developer - Development access",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Player - Regular user after login",
                            Name = "Player"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Guest - User without login",
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@rogue-kie.local",
                            IsActive = true,
                            Password = "$2a$11$XvzDRR5slzvRSaXyiU9XSuf1jQST.ienOHTpBa5wBb6Z4Oxw5q4ae",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guest@rogue-kie.local",
                            IsActive = true,
                            Password = "$2a$11$JR24rcgcbVZeFgPTVFaFZOZ3JPKV1y42R9GGFz3mZtwHbjnzCSjTO",
                            RoleId = 4,
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WeaponConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BulletId")
                        .HasColumnType("integer");

                    b.Property<int>("BulletsPerShot")
                        .HasColumnType("integer");

                    b.Property<float>("FireRate")
                        .HasColumnType("real");

                    b.Property<float>("HandPositionX")
                        .HasColumnType("real");

                    b.Property<float>("HandPositionY")
                        .HasColumnType("real");

                    b.Property<float>("HandPositionZ")
                        .HasColumnType("real");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("RecoilDistance")
                        .HasColumnType("real");

                    b.Property<float>("RecoilDuration")
                        .HasColumnType("real");

                    b.Property<float>("ReturnDuration")
                        .HasColumnType("real");

                    b.Property<string>("ShootSound")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("ShootVolume")
                        .HasColumnType("real");

                    b.Property<float>("SpreadAngle")
                        .HasColumnType("real");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BulletId");

                    b.ToTable("WeaponConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BulletId = 1,
                            BulletsPerShot = 1,
                            FireRate = 0.5f,
                            HandPositionX = 0.1f,
                            HandPositionY = 0.05f,
                            HandPositionZ = 0f,
                            ManaCost = 0,
                            PrefabName = "PistolPrefab",
                            RecoilDistance = 0.1f,
                            RecoilDuration = 0.05f,
                            ReturnDuration = 0.1f,
                            ShootSound = "pistol_shoot",
                            ShootVolume = 1f,
                            SpreadAngle = 2f,
                            WeaponName = "Pistol"
                        },
                        new
                        {
                            Id = 2,
                            BulletId = 2,
                            BulletsPerShot = 5,
                            FireRate = 1.5f,
                            HandPositionX = 0.2f,
                            HandPositionY = 0.1f,
                            HandPositionZ = 0f,
                            ManaCost = 2,
                            PrefabName = "ShotgunPrefab",
                            RecoilDistance = 0.3f,
                            RecoilDuration = 0.1f,
                            ReturnDuration = 0.2f,
                            ShootSound = "shotgun_shoot",
                            ShootVolume = 1.2f,
                            SpreadAngle = 15f,
                            WeaponName = "Shotgun"
                        },
                        new
                        {
                            Id = 3,
                            BulletId = 3,
                            BulletsPerShot = 1,
                            FireRate = 2f,
                            HandPositionX = 0.3f,
                            HandPositionY = 0.15f,
                            HandPositionZ = 0f,
                            ManaCost = 5,
                            PrefabName = "SniperPrefab",
                            RecoilDistance = 0.5f,
                            RecoilDuration = 0.15f,
                            ReturnDuration = 0.3f,
                            ShootSound = "sniper_shoot",
                            ShootVolume = 1.5f,
                            SpreadAngle = 0f,
                            WeaponName = "Sniper"
                        },
                        new
                        {
                            Id = 4,
                            BulletId = 4,
                            BulletsPerShot = 1,
                            FireRate = 0.2f,
                            HandPositionX = 0.2f,
                            HandPositionY = 0.1f,
                            HandPositionZ = 0f,
                            ManaCost = 1,
                            PrefabName = "RiflePrefab",
                            RecoilDistance = 0.15f,
                            RecoilDuration = 0.05f,
                            ReturnDuration = 0.1f,
                            ShootSound = "rifle_shoot",
                            ShootVolume = 0.8f,
                            SpreadAngle = 5f,
                            WeaponName = "Assault Rifle"
                        },
                        new
                        {
                            Id = 5,
                            BulletId = 5,
                            BulletsPerShot = 1,
                            FireRate = 0.8f,
                            HandPositionX = 0.1f,
                            HandPositionY = 0.2f,
                            HandPositionZ = 0f,
                            ManaCost = 0,
                            PrefabName = "SwordPrefab",
                            RecoilDistance = 0f,
                            RecoilDuration = 0f,
                            ReturnDuration = 0f,
                            ShootSound = "sword_swing",
                            ShootVolume = 1f,
                            SpreadAngle = 30f,
                            WeaponName = "Sword"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.User", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WeaponConfig", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.BulletConfig", "BulletConfig")
                        .WithMany()
                        .HasForeignKey("BulletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BulletConfig");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
