// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rogue_Kie.BE.DataAccess.DBContext;

#nullable disable

namespace Rogue_Kie.BE.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703143111_SeedGameConfigs")]
    partial class SeedGameConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.BuffConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuffName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BuffType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("BuffConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuffName = "Speed Boost",
                            BuffType = "StatModifier",
                            Description = "Increases movement speed.",
                            IconPath = "speed_icon",
                            Rarity = "Common",
                            Value = 1.5f
                        },
                        new
                        {
                            Id = 2,
                            BuffName = "Damage Boost",
                            BuffType = "StatModifier",
                            Description = "Increases damage dealt.",
                            IconPath = "damage_icon",
                            Rarity = "Rare",
                            Value = 2f
                        },
                        new
                        {
                            Id = 3,
                            BuffName = "Health Regen",
                            BuffType = "Utility",
                            Description = "Regenerates health over time.",
                            IconPath = "regen_icon",
                            Rarity = "Epic",
                            Value = 10f
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.EnemyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EnemyConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackSpeed = 1.5f,
                            BaseDamage = 10,
                            BaseHealth = 50,
                            EnemyName = "Slime",
                            MoveSpeed = 2f,
                            PrefabName = "SlimePrefab"
                        },
                        new
                        {
                            Id = 2,
                            AttackSpeed = 1.2f,
                            BaseDamage = 15,
                            BaseHealth = 100,
                            EnemyName = "Goblin",
                            MoveSpeed = 3.5f,
                            PrefabName = "GoblinPrefab"
                        },
                        new
                        {
                            Id = 3,
                            AttackSpeed = 2f,
                            BaseDamage = 30,
                            BaseHealth = 250,
                            EnemyName = "Orc",
                            MoveSpeed = 1.5f,
                            PrefabName = "OrcPrefab"
                        },
                        new
                        {
                            Id = 4,
                            AttackSpeed = 0.5f,
                            BaseDamage = 100,
                            BaseHealth = 1000,
                            EnemyName = "Dragon",
                            MoveSpeed = 5f,
                            PrefabName = "DragonPrefab"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.LevelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DifficultyMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEnemiesToSpawn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LevelConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyMultiplier = 1f,
                            FloorNumber = 1,
                            MaxEnemiesToSpawn = 10
                        },
                        new
                        {
                            Id = 2,
                            DifficultyMultiplier = 1.2f,
                            FloorNumber = 2,
                            MaxEnemiesToSpawn = 15
                        },
                        new
                        {
                            Id = 3,
                            DifficultyMultiplier = 1.5f,
                            FloorNumber = 3,
                            MaxEnemiesToSpawn = 25
                        },
                        new
                        {
                            Id = 4,
                            DifficultyMultiplier = 2f,
                            FloorNumber = 4,
                            MaxEnemiesToSpawn = 40
                        },
                        new
                        {
                            Id = 5,
                            DifficultyMultiplier = 3f,
                            FloorNumber = 5,
                            MaxEnemiesToSpawn = 1
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RegistrationOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("RegistrationOtps", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator - Full access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Developer - Development access",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Player - Regular user after login",
                            Name = "Player"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Guest - User without login",
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@rogue-kie.local",
                            Password = "$2a$11$C24MGKhdP9qoPh3GdRNVvO4rUsY5REvy8J/S4C9qrYZ.7ZYf1Q3Si",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "guest@rogue-kie.local",
                            Password = "$2a$11$98t77WPOjsGRv69nkgb7NeBJHJsiSJ2EzmvqaImddhoMWPa54Eqe2",
                            RoleId = 4,
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WeaponConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<float>("FireRate")
                        .HasColumnType("real");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("WeaponConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 20,
                            FireRate = 0.5f,
                            WeaponName = "Pistol"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 50,
                            FireRate = 1.5f,
                            WeaponName = "Shotgun"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 150,
                            FireRate = 2f,
                            WeaponName = "Sniper"
                        },
                        new
                        {
                            Id = 4,
                            Damage = 30,
                            FireRate = 0.2f,
                            WeaponName = "Assault Rifle"
                        },
                        new
                        {
                            Id = 5,
                            Damage = 40,
                            FireRate = 0.8f,
                            WeaponName = "Sword"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.User", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
