// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rogue_Kie.BE.DataAccess.DBContext;

#nullable disable

namespace Rogue_Kie.BE.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728132634_AddWeaponTypeAndRarity")]
    partial class AddWeaponTypeAndRarity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.BuffConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuffName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BuffType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("BuffConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuffName = "Vitality",
                            BuffType = "MaxHP",
                            Description = "Increases Max HP by +2 and heals.",
                            IconPath = "hp_icon",
                            Rarity = "Common",
                            Value = 2f
                        },
                        new
                        {
                            Id = 2,
                            BuffName = "Swift Foot",
                            BuffType = "MoveSpeed",
                            Description = "Increases movement speed by +15%.",
                            IconPath = "speed_icon",
                            Rarity = "Common",
                            Value = 1.15f
                        },
                        new
                        {
                            Id = 3,
                            BuffName = "Fierce Combat",
                            BuffType = "Damage",
                            Description = "Increases all weapon damage by +20%.",
                            IconPath = "damage_icon",
                            Rarity = "Common",
                            Value = 1.2f
                        },
                        new
                        {
                            Id = 4,
                            BuffName = "Magic Focus",
                            BuffType = "MaxMana",
                            Description = "Increases Max Mana by +50 and refills it.",
                            IconPath = "mana_icon",
                            Rarity = "Common",
                            Value = 50f
                        },
                        new
                        {
                            Id = 5,
                            BuffName = "Golden Touch",
                            BuffType = "CoinMultiplier",
                            Description = "Increases picked up coins by +50%.",
                            IconPath = "coin_icon",
                            Rarity = "Common",
                            Value = 1.5f
                        },
                        new
                        {
                            Id = 6,
                            BuffName = "Sharp Focus",
                            BuffType = "CritChance",
                            Description = "Increases crit rate by +15%.",
                            IconPath = "crit_icon",
                            Rarity = "Common",
                            Value = 15f
                        },
                        new
                        {
                            Id = 7,
                            BuffName = "Rapid Fire",
                            BuffType = "FireRate",
                            Description = "Decreases gun firing cooldown by 20%.",
                            IconPath = "firerate_icon",
                            Rarity = "Common",
                            Value = 0.8f
                        },
                        new
                        {
                            Id = 8,
                            BuffName = "Iron Armor",
                            BuffType = "MaxArmor",
                            Description = "Increases Max Armor by +2 and refills armor.",
                            IconPath = "armor_icon",
                            Rarity = "Common",
                            Value = 2f
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.BulletConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BulletName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("CritMultiplier")
                        .HasColumnType("real");

                    b.Property<float>("CritRate")
                        .HasColumnType("real");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<float>("FlightSpeed")
                        .HasColumnType("real");

                    b.Property<int>("PiercingCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("BulletConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BulletName = "Basic Bullet",
                            CritMultiplier = 1.5f,
                            CritRate = 0.1f,
                            Damage = 20,
                            FlightSpeed = 10f,
                            PiercingCount = 0,
                            PrefabName = "BasicBulletPrefab"
                        },
                        new
                        {
                            Id = 2,
                            BulletName = "Buckshot",
                            CritMultiplier = 1.5f,
                            CritRate = 0.05f,
                            Damage = 10,
                            FlightSpeed = 15f,
                            PiercingCount = 0,
                            PrefabName = "BuckshotPrefab"
                        },
                        new
                        {
                            Id = 3,
                            BulletName = "Sniper Round",
                            CritMultiplier = 2f,
                            CritRate = 0.5f,
                            Damage = 150,
                            FlightSpeed = 30f,
                            PiercingCount = 3,
                            PrefabName = "SniperRoundPrefab"
                        },
                        new
                        {
                            Id = 4,
                            BulletName = "Rifle Bullet",
                            CritMultiplier = 1.5f,
                            CritRate = 0.2f,
                            Damage = 30,
                            FlightSpeed = 20f,
                            PiercingCount = 1,
                            PrefabName = "RifleBulletPrefab"
                        },
                        new
                        {
                            Id = 5,
                            BulletName = "Sword Slash",
                            CritMultiplier = 2f,
                            CritRate = 0.3f,
                            Damage = 40,
                            FlightSpeed = 5f,
                            PiercingCount = 99,
                            PrefabName = "SwordSlashPrefab"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CharacterId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkillSet")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UnlockPrice")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters", (string)null);

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            BaseDamage = 15,
                            BaseHealth = 100,
                            CurrencyType = "Gold",
                            Description = "A brave warrior from Kie kingdom",
                            Name = "Kie Warrior",
                            SkillSet = "Slash, Shield",
                            UnlockPrice = 0
                        },
                        new
                        {
                            CharacterId = 2,
                            BaseDamage = 25,
                            BaseHealth = 80,
                            CurrencyType = "Gold",
                            Description = "A master of elements from Kie academy",
                            Name = "Kie Mage",
                            SkillSet = "Fireball, Teleport",
                            UnlockPrice = 100
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.CosmeticItem", b =>
                {
                    b.Property<int>("CosmeticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CosmeticId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CosmeticId"));

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CosmeticId");

                    b.ToTable("CosmeticItems", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.EnemyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("MoveSpeed")
                        .HasColumnType("real");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EnemyConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackSpeed = 1.5f,
                            BaseDamage = 10,
                            BaseHealth = 50,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Slime",
                            MoveSpeed = 2f,
                            PrefabName = "SlimePrefab"
                        },
                        new
                        {
                            Id = 2,
                            AttackSpeed = 1.2f,
                            BaseDamage = 15,
                            BaseHealth = 100,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Goblin",
                            MoveSpeed = 3.5f,
                            PrefabName = "GoblinPrefab"
                        },
                        new
                        {
                            Id = 3,
                            AttackSpeed = 2f,
                            BaseDamage = 30,
                            BaseHealth = 250,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Orc",
                            MoveSpeed = 1.5f,
                            PrefabName = "OrcPrefab"
                        },
                        new
                        {
                            Id = 4,
                            AttackSpeed = 0.5f,
                            BaseDamage = 100,
                            BaseHealth = 1000,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnemyName = "Dragon",
                            MoveSpeed = 5f,
                            PrefabName = "DragonPrefab"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.GameSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SessionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HostUserId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("RoomCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SessionId");

                    b.HasIndex("HostUserId");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("InventoryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InventoryId"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.HasKey("InventoryId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Leaderboard", b =>
                {
                    b.Property<int>("LeaderboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LeaderboardId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaderboardId"));

                    b.Property<int>("HighestWave")
                        .HasColumnType("integer");

                    b.Property<int>("RankPosition")
                        .HasColumnType("integer");

                    b.Property<int>("TotalKills")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LeaderboardId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Leaderboards", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.LevelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LevelConfigId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DifficultyMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LevelConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyMultiplier = 1f,
                            FloorNumber = 1,
                            StageId = 1
                        },
                        new
                        {
                            Id = 2,
                            DifficultyMultiplier = 1.2f,
                            FloorNumber = 2,
                            StageId = 1
                        },
                        new
                        {
                            Id = 3,
                            DifficultyMultiplier = 1.5f,
                            FloorNumber = 3,
                            StageId = 1
                        },
                        new
                        {
                            Id = 4,
                            DifficultyMultiplier = 2f,
                            FloorNumber = 4,
                            StageId = 1
                        },
                        new
                        {
                            Id = 5,
                            DifficultyMultiplier = 3f,
                            FloorNumber = 5,
                            StageId = 1
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ProfileId");

                    b.ToTable("PlayerCharacters", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerCosmetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CosmeticId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CosmeticId");

                    b.HasIndex("ProfileId");

                    b.ToTable("PlayerCosmetics", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ProfileId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("HighestWave")
                        .HasColumnType("integer");

                    b.Property<int>("PremiumCurrency")
                        .HasColumnType("integer");

                    b.Property<int>("StandardCurrency")
                        .HasColumnType("integer");

                    b.Property<int>("TotalKills")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeaponConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("WeaponConfigId");

                    b.ToTable("PlayerWeapons", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrator - Full access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Developer - Development access",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Player - Regular user after login",
                            Name = "Player"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Guest - User without login",
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RoomConfig", b =>
                {
                    b.Property<int>("RoomConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoomConfigId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomConfigId"));

                    b.Property<int>("LevelConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalWavesInRoom")
                        .HasColumnType("integer");

                    b.HasKey("RoomConfigId");

                    b.HasIndex("LevelConfigId");

                    b.ToTable("RoomConfigs", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RoomWaveConfig", b =>
                {
                    b.Property<int>("RoomWaveConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoomWaveConfigId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomWaveConfigId"));

                    b.Property<int>("MaxSimultaneousMonsters")
                        .HasColumnType("integer");

                    b.Property<int>("RoomConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("WaveNumber")
                        .HasColumnType("integer");

                    b.HasKey("RoomWaveConfigId");

                    b.HasIndex("RoomConfigId");

                    b.ToTable("RoomWaveConfigs", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RunHistory", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RunId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RunId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyEarned")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("EnemiesKilled")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WavesSurvived")
                        .HasColumnType("integer");

                    b.HasKey("RunId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("RunHistories", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.SessionPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionPlayers", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.ShopItem", b =>
                {
                    b.Property<int>("ShopItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ShopItemId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopItemId"));

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("ShopItemId");

                    b.ToTable("ShopItems", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TransactionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@rogue-kie.local",
                            IsActive = true,
                            Password = "$2a$11$T1339EUj.Aj1X11HrzHxUOm0za0sGj/Toc2vg4c3Gytf7F/8X6gha",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guest@rogue-kie.local",
                            IsActive = true,
                            Password = "$2a$11$WkCZ3YyNRQgy9bVunDD6PuyqEyYURaA/DhLfYYsdlo7isx5CwrlQq",
                            RoleId = 4,
                            Username = "guest"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WaveEnemyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnemyConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RoomWaveConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnemyConfigId");

                    b.HasIndex("RoomWaveConfigId");

                    b.ToTable("WaveEnemyDetails", (string)null);
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WeaponConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BulletId")
                        .HasColumnType("integer");

                    b.Property<int>("BulletsPerShot")
                        .HasColumnType("integer");

                    b.Property<float>("FireRate")
                        .HasColumnType("real");

                    b.Property<float>("HandPositionX")
                        .HasColumnType("real");

                    b.Property<float>("HandPositionY")
                        .HasColumnType("real");

                    b.Property<float>("HandPositionZ")
                        .HasColumnType("real");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer");

                    b.Property<string>("PrefabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("RecoilDistance")
                        .HasColumnType("real");

                    b.Property<float>("RecoilDuration")
                        .HasColumnType("real");

                    b.Property<float>("ReturnDuration")
                        .HasColumnType("real");

                    b.Property<string>("ShootSound")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("ShootVolume")
                        .HasColumnType("real");

                    b.Property<float>("SpreadAngle")
                        .HasColumnType("real");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BulletId");

                    b.ToTable("WeaponConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BulletId = 1,
                            BulletsPerShot = 1,
                            FireRate = 0.5f,
                            HandPositionX = 0.1f,
                            HandPositionY = 0.05f,
                            HandPositionZ = 0f,
                            ManaCost = 0,
                            PrefabName = "PistolPrefab",
                            Rarity = "Common",
                            RecoilDistance = 0.1f,
                            RecoilDuration = 0.05f,
                            ReturnDuration = 0.1f,
                            ShootSound = "pistol_shoot",
                            ShootVolume = 1f,
                            SpreadAngle = 2f,
                            WeaponName = "Pistol",
                            WeaponType = "Pistol"
                        },
                        new
                        {
                            Id = 2,
                            BulletId = 2,
                            BulletsPerShot = 5,
                            FireRate = 1.5f,
                            HandPositionX = 0.2f,
                            HandPositionY = 0.1f,
                            HandPositionZ = 0f,
                            ManaCost = 2,
                            PrefabName = "ShotgunPrefab",
                            Rarity = "Rare",
                            RecoilDistance = 0.3f,
                            RecoilDuration = 0.1f,
                            ReturnDuration = 0.2f,
                            ShootSound = "shotgun_shoot",
                            ShootVolume = 1.2f,
                            SpreadAngle = 15f,
                            WeaponName = "Shotgun",
                            WeaponType = "Shotgun"
                        },
                        new
                        {
                            Id = 3,
                            BulletId = 3,
                            BulletsPerShot = 1,
                            FireRate = 2f,
                            HandPositionX = 0.3f,
                            HandPositionY = 0.15f,
                            HandPositionZ = 0f,
                            ManaCost = 5,
                            PrefabName = "SniperPrefab",
                            Rarity = "Epic",
                            RecoilDistance = 0.5f,
                            RecoilDuration = 0.15f,
                            ReturnDuration = 0.3f,
                            ShootSound = "sniper_shoot",
                            ShootVolume = 1.5f,
                            SpreadAngle = 0f,
                            WeaponName = "Sniper",
                            WeaponType = "Sniper"
                        },
                        new
                        {
                            Id = 4,
                            BulletId = 4,
                            BulletsPerShot = 1,
                            FireRate = 0.2f,
                            HandPositionX = 0.2f,
                            HandPositionY = 0.1f,
                            HandPositionZ = 0f,
                            ManaCost = 1,
                            PrefabName = "RiflePrefab",
                            Rarity = "Common",
                            RecoilDistance = 0.15f,
                            RecoilDuration = 0.05f,
                            ReturnDuration = 0.1f,
                            ShootSound = "rifle_shoot",
                            ShootVolume = 0.8f,
                            SpreadAngle = 5f,
                            WeaponName = "Assault Rifle",
                            WeaponType = "Rifle"
                        },
                        new
                        {
                            Id = 5,
                            BulletId = 5,
                            BulletsPerShot = 1,
                            FireRate = 0.8f,
                            HandPositionX = 0.1f,
                            HandPositionY = 0.2f,
                            HandPositionZ = 0f,
                            ManaCost = 0,
                            PrefabName = "SwordPrefab",
                            Rarity = "Rare",
                            RecoilDistance = 0f,
                            RecoilDuration = 0f,
                            ReturnDuration = 0f,
                            ShootSound = "sword_swing",
                            ShootVolume = 1f,
                            SpreadAngle = 30f,
                            WeaponName = "Sword",
                            WeaponType = "Melee"
                        });
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.GameSession", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "HostUser")
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HostUser");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Inventory", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Leaderboard", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Rogue_Kie.BE.DataAccess.Models.Leaderboard", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerCharacter", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerCosmetic", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.CosmeticItem", "CosmeticItem")
                        .WithMany()
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosmeticItem");

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.PlayerWeapon", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.WeaponConfig", "WeaponConfig")
                        .WithMany()
                        .HasForeignKey("WeaponConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("WeaponConfig");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RefreshToken", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RoomConfig", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.LevelConfig", "LevelConfig")
                        .WithMany()
                        .HasForeignKey("LevelConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelConfig");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RoomWaveConfig", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.RoomConfig", "RoomConfig")
                        .WithMany()
                        .HasForeignKey("RoomConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomConfig");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.RunHistory", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.SessionPlayer", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Transaction", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.User", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WaveEnemyDetail", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.EnemyConfig", "EnemyConfig")
                        .WithMany()
                        .HasForeignKey("EnemyConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.RoomWaveConfig", "RoomWaveConfig")
                        .WithMany()
                        .HasForeignKey("RoomWaveConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnemyConfig");

                    b.Navigation("RoomWaveConfig");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.WeaponConfig", b =>
                {
                    b.HasOne("Rogue_Kie.BE.DataAccess.Models.BulletConfig", "BulletConfig")
                        .WithMany()
                        .HasForeignKey("BulletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BulletConfig");
                });

            modelBuilder.Entity("Rogue_Kie.BE.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
